import storeImg_1 from "./image/storeImg/storeImg_1.jpeg";
import storeImg_2 from "./image/storeImg/storeImg_2.jpeg";
import storeImg_3 from "./image/storeImg/storeImg_3.jpeg";
import storeImg_4 from "./image/storeImg/storeImg_4.jpeg";
import storeImg_5 from "./image/storeImg/storeImg_5.jpg";
import storeImg_6 from "./image/storeImg/storeImg_6.jpg";
import storeImg_7 from "./image/storeImg/storeImg_7.jpeg";
import storeImg_8 from "./image/storeImg/storeImg_8.jpg";
import storeImg_9 from "./image/storeImg/storeImg_9.jpg";
import storeImg_10 from "./image/storeImg/storeImg_10.jpeg";
import storeImg_11 from "./image/storeImg/storeImg_11.jpg";
import storeImg_12 from "./image/storeImg/storeImg_12.jpg";

const data = [
  {
    address: "110台北市信義區松仁路253巷1弄2號",
    businessHour: ["10:30–20:00"],
    category: "healthy",
    phoneNumber: "+886227207471",
    title: "橄欖油健康餐盒",
    photo: storeImg_1,
    id: "AAA0001",
    menu: [
      {
        name: "舒肥墨西哥烤",
        price: 180,
        class: "經典舒肥系列",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0001",
      },
      {
        name: "法式舒肥櫻桃鴨胸",
        price: 230,
        class: "經典舒肥系列",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0002",
      },
      {
        name: "舒肥雞肉輕食餐",
        price: 150,
        class: "經典舒肥系列",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0003",
      },
      {
        name: "舒肥牛小排輕食餐",
        price: 260,
        class: "經典舒肥系列",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0004",
      },
      {
        name: "舒肥鮭魚菲力輕食餐",
        price: 260,
        class: "經典舒肥系列",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0005",
      },
      {
        name: "紅酒燉牛肋條",
        price: 190,
        class: "燉肉餐盒",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0006",
      },
      {
        name: "獵人燉雞腿",
        price: 150,
        class: "燉肉餐盒",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0007",
      },
      {
        name: "DELI法式櫻桃鴨沙拉",
        price: 230,
        class: "沙拉",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0008",
      },
      {
        name: "DELI墨西哥烤豬沙拉",
        price: 180,
        class: "沙拉",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0009",
      },
      {
        name: "DELI 水果生菜沙拉",
        price: 150,
        class: "沙拉",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0010",
      },
      {
        name: "DELI 雞胸肉沙拉",
        price: 150,
        class: "沙拉",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0011",
      },
      {
        name: "DELI 牛小排沙拉",
        price: 260,
        class: "沙拉",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0012",
      },
      {
        name: "DELI 鮭魚沙拉",
        price: 260,
        class: "沙拉",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0013",
      },
      {
        name: "地中海風味當季時蔬",
        price: 180,
        class: "素食餐盒",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0014",
      },
      {
        name: "南瓜濃湯",
        price: 80,
        class: "湯品",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0015",
      },
      {
        name: "義式蔬菜湯（素）",
        price: 60,
        class: "湯品",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0016",
      },
      {
        name: "法式洋蔥湯",
        price: 60,
        class: "湯品",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0017",
      },
      {
        name: "美式咖啡",
        price: 50,
        class: "飲料",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0018",
      },
      {
        name: "甜菊紅茶",
        price: 35,
        class: "飲料",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0019",
      },
      {
        name: "蜂蜜檸檬汁（冰）",
        price: 65,
        class: "飲料",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0020",
      },
      {
        name: "水煮蛋",
        price: 20,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0021",
      },
      {
        name: "低溫雞胸肉",
        price: 60,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0022",
      },
      {
        name: "低溫牛小排",
        price: 190,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0023",
      },
      {
        name: "低溫鮭魚菲力",
        price: 190,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0001_0024",
      },
    ],
  },
  {
    address: "110台北市信義區忠孝東路四段553巷2弄5號",
    businessHour: [" 11:30–21:00"],
    category: "western",
    phoneNumber: "+886227531881",
    title: "一直是晴天",
    photo: storeImg_2,
    id: "AAA0002",
    menu: [
      {
        name: "百香雙Q果",
        price: null,
        class: "鮮果茶飲",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 160, canChooseIce: true },
          { size: "Bottle", price: 190, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0001",
      },
      {
        name: "百香雙Q果",
        price: null,
        class: "鮮果茶飲",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 60, canChooseIce: true },
          { size: "Bottle", price: 90, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0001",
      },
      {
        name: "百香雙Q果",
        price: null,
        class: "鮮果茶飲",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 60, canChooseIce: true },
          { size: "Bottle", price: 90, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0001",
      },
      {
        name: "卡哩卡哩雞腿沙拉",
        price: 200,
        class: "早午餐、沙拉餐",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0001",
      },
      {
        name: "碳烤牛肉沙拉",
        price: 200,
        class: "早午餐、沙拉餐",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0002",
      },
      {
        name: "手工蔥餅佐醬燒牛肉",
        price: 220,
        class: "早午餐、沙拉餐",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0003",
      },
      {
        name: "香煎松阪豬沙拉",
        price: 220,
        class: "早午餐、沙拉餐",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0004",
      },
      {
        name: "煎烤牛小排沙拉",
        price: 320,
        class: "早午餐、沙拉餐",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0005",
      },
      {
        name: "義式炒海鮮沙拉",
        price: 320,
        class: "早午餐、沙拉餐",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0006",
      },
      {
        name: "檸香雞腿飯",
        price: 200,
        class: "吃飯飯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0007",
      },
      {
        name: "碳烤牛肉飯",
        price: 200,
        class: "吃飯飯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0008",
      },
      {
        name: "塔香咕咕雞",
        price: 200,
        class: "吃飯飯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0009",
      },
      {
        name: "煎烤牛小排飯",
        price: 300,
        class: "吃飯飯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0010",
      },
      {
        name: "鮮蔬什錦丼飯",
        price: 200,
        class: "吃飯飯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0011",
      },
      {
        name: "時蔬衝爆牛肉飯",
        price: 220,
        class: "吃飯飯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0012",
      },
      {
        name: "香煎松阪豬佐時蔬",
        price: 220,
        class: "吃飯飯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0013",
      },
      {
        name: "招牌蕃茄肉醬義大利麵",
        price: 180,
        class: "吃麵麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0014",
      },
      {
        name: "和風柚香鮮蔬義大利麵",
        price: 180,
        class: "吃麵麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0015",
      },
      {
        name: "辣味轟炸雞義大利麵",
        price: 200,
        class: "吃麵麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0016",
      },
      {
        name: "蒜香煎烤雞肉義大利麵",
        price: 200,
        class: "吃麵麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0017",
      },
      {
        name: "義式雪花牛肉義大利麵",
        price: 200,
        class: "吃麵麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0018",
      },
      {
        name: "酥炸花枝蒜辣義大利麵",
        price: 200,
        class: "吃麵麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0019",
      },
      {
        name: "蒜香煎烤牛小排義大利麵",
        price: 300,
        class: "吃麵麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0020",
      },
      {
        name: "爆蒜辣炒海鮮義大利麵",
        price: 300,
        class: "吃麵麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0002_0021",
      },
    ],
  },
  {
    address: "台北市信義區基隆路二段10號",
    businessHour: ["17:00-03:00"],
    category: "western",
    phoneNumber: "8786-8858",
    title: "角窩美式餐酒館",
    photo: storeImg_3,
    id: "AAA0003",
    menu: [
      {
        name: "凱薩沙拉",
        price: 180,
        class: "沙拉",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0003_0001",
      },
      {
        name: "雞肉沙拉",
        price: 200,
        class: "沙拉",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0003_0002",
      },
      {
        name: "⽜肉沙拉",
        price: 220,
        class: "沙拉",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0003_0003",
      },
      {
        name: "醬烤雞胸古巴三明治",
        price: 300,
        class: "古巴三明治",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0003_0004",
      },
      {
        name: "黑咖⼿撕豬古巴三明治",
        price: 320,
        class: "古巴三明治",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0003_0005",
      },
      {
        name: "悶烤⽜胸古巴三明治",
        price: 380,
        class: "古巴三明治",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0003_0006",
      },
      {
        name: "工人放飯",
        price: 200,
        class: "角窩鍋飯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0003_0007",
      },
      {
        name: "工頭開飯",
        price: 220,
        class: "角窩鍋飯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0003_0008",
      },
      {
        name: "加州海鮮比薩",
        price: 280,
        class: "8寸比薩",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0003_0009",
      },
      {
        name: "夏威夷比薩",
        price: 250,
        class: "8寸比薩",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0003_0010",
      },
      {
        name: "墨西哥臘腸比",
        price: 280,
        class: "8寸比薩",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0003_0011",
      },
      {
        name: "燻烤豬肋排",
        price: 450,
        class: "排餐",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0003_0012",
      },
      {
        name: "加州風味雞腿排",
        price: 390,
        class: "排餐",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0003_0013",
      },
    ],
  },
  {
    address: "110台北市信義區忠孝東路四段553巷2弄11號",
    businessHour: ["10:30–14:00", "15:00–19:00"],
    category: "healthy",
    phoneNumber: "+886227669669",
    title: "給力盒子",
    photo: storeImg_4,
    id: "AAA0004",
    menu: [
      {
        name: "墨西哥火烤雞胸",
        price: 158,
        class: "人氣精選",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0004_0001",
      },
      {
        name: "蒜泥低脂豬肉片",
        price: 148,
        class: "人氣精選",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0004_0002",
      },
      {
        name: "香蒜水煮雞胸",
        price: 158,
        class: "人氣精選",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0004_0003",
      },
      {
        name: "義式香草烤雞腿排",
        price: 168,
        class: "人氣精選",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0004_0004",
      },
      {
        name: "肉多多特餐",
        price: 178,
        class: "人氣精選",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0004_0005",
      },
    ],
  },
  {
    address: "110台北市信義區忠孝東路五段17之2號",
    businessHour: ["10:00–22:00"],
    category: "beverage",
    phoneNumber: "+886227680808",
    title: "可不可",
    photo: storeImg_5,
    id: "AAA0005",
    menu: [
      {
        name: "熟成紅茶",
        price: null,
        class: "紅茶",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 30, canChooseIce: true },
          { size: "L", price: 35, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
        id: "AAA0005_0001",
      },
      {
        name: "麗春紅茶",
        price: null,
        class: "紅茶",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 30, canChooseIce: true },
          { size: "L", price: 35, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
        id: "AAA0005_0002",
      },
      {
        name: "太妃紅茶",
        price: null,
        class: "紅茶",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 35, canChooseIce: true },
          { size: "L", price: 40, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
        id: "AAA0005_0003",
      },
      {
        name: "胭脂紅茶",
        price: null,
        class: "紅茶",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 40, canChooseIce: true },
          { size: "L", price: 45, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
        id: "AAA0005_0004",
      },
      {
        name: "雪藏紅茶",
        price: null,
        class: "紅茶",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 50, canChooseIce: true },
          { size: "L", price: 60, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
        id: "AAA0005_0005",
      },
      {
        name: "熟成冷露",
        price: null,
        class: "冷露",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 30, canChooseIce: true },
          { size: "L", price: 35, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
        id: "AAA0005_0006",
      },
      {
        name: "雪花冷露",
        price: null,
        class: "冷露",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 30, canChooseIce: true },
          { size: "L", price: 35, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
        id: "AAA0005_0007",
      },
      {
        name: "春芽冷露",
        price: null,
        class: "冷露",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 30, canChooseIce: true },
          { size: "L", price: 35, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
        id: "AAA0005_0008",
      },
      {
        name: "春芽綠茶",
        price: null,
        class: "茶",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 30, canChooseIce: true },
          { size: "L", price: 35, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
        id: "AAA0005_0009",
      },
      {
        name: "春梅冰茶",
        price: null,
        class: "茶",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 40, canChooseIce: true },
          { size: "L", price: 50, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
        id: "AAA0005_0010",
      },
      {
        name: "冷露歐蕾",
        price: null,
        class: "歐蕾",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 45, canChooseIce: true },
          { size: "L", price: 55, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
        id: "AAA0005_0011",
      },
      {
        name: "熟成歐蕾",
        price: null,
        class: "歐蕾",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 45, canChooseIce: true },
          { size: "L", price: 55, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
        id: "AAA0005_0012",
      },
      {
        name: "白玉歐蕾",
        price: null,
        class: "歐蕾",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 55, canChooseIce: true },
          { size: "L", price: 65, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
        id: "AAA0005_0013",
      },
      {
        name: "黃玉歐蕾",
        price: null,
        class: "歐蕾",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 65, canChooseIce: true },
          { size: "L", price: 75, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
        id: "AAA0005_0014",
      },
      {
        name: "胭脂多多",
        price: null,
        class: "其他",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 45, canChooseIce: true },
          { size: "L", price: 55, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
        id: "AAA0005_0015",
      },
      {
        name: "雪藏末茶",
        price: null,
        class: "其他",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 55, canChooseIce: true },
          { size: "L", price: 65, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
        id: "AAA0005_0016",
      },
    ],
  },
  {
    address: "110台北市信義區忠孝東路四段559巷18之1號",
    businessHour: ["11:00–20:30"],
    category: "eastern",
    phoneNumber: "+886227493472",
    title: "味家魯肉飯",
    photo: storeImg_6,
    id: "AAA0006",
    menu: [
      {
        name: "舌頭肉",
        price: 50,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0001",
      },
      {
        name: "豬舌頭",
        price: 50,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0002",
      },
      {
        name: "豬肝𦟪",
        price: 50,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0003",
      },
      {
        name: "滷蛋",
        price: 10,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0004",
      },
      {
        name: "油豆腐",
        price: 10,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0005",
      },
      {
        name: "白菜滷",
        price: 30,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0006",
      },
      {
        name: "筍絲",
        price: 30,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0007",
      },
      {
        name: "燙青菜",
        price: 30,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0008",
      },
      {
        name: "肉燥乾油麵",
        price: 45,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0009",
      },
      {
        name: "肉燥乾米粉",
        price: 45,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0010",
      },
      {
        name: "肉羹麵",
        price: 50,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0011",
      },
      {
        name: "肉羹米粉",
        price: 50,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0012",
      },
      {
        name: "肉羹冬粉",
        price: 50,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0013",
      },
      {
        name: "肉羹",
        price: 40,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0014",
      },
      {
        name: "排骨酥湯麵",
        price: 55,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0015",
      },
      {
        name: "排骨酥湯米粉",
        price: 55,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0016",
      },
      {
        name: "排骨酥湯冬粉",
        price: 55,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0017",
      },
      {
        name: "鳳梨苦瓜雞湯",
        price: 50,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0018",
      },
      {
        name: "蛤仔雞湯",
        price: 50,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0019",
      },
      {
        name: "排骨酥湯",
        price: 45,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0020",
      },
      {
        name: "筒仔米糕",
        price: 30,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0021",
      },
      {
        name: "控肉飯",
        price: 80,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0022",
      },
      {
        name: "魯肉飯便當",
        price: 75,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0023",
      },
      {
        name: "魯肉飯（大）",
        price: 40,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0024",
      },
      {
        name: "魯肉飯（小）",
        price: 25,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0006_0025",
      },
    ],
  },
  {
    address: "110台北市信義區忠孝東路四段559巷16弄7號",
    businessHour: ["unknow"],
    category: "eastern",
    phoneNumber: "+886227458198",
    title: "台灣阿誠現炒菜",
    photo: storeImg_7,
    id: "AAA0007",
    menu: [
      {
        name: "牛肉蛋炒飯",
        price: 90,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0007_0001",
      },
      {
        name: "蝦仁肉絲蛋炒飯",
        price: 90,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0007_0002",
      },
      {
        name: "海鮮什錦炒麵",
        price: 90,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0007_0003",
      },
      {
        name: "牛肉炒麵",
        price: 90,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0007_0004",
      },
      {
        name: "肉絲炒麵",
        price: 90,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0007_0005",
      },
      {
        name: "招牌煎蛋",
        price: 130,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0007_0006",
      },
      {
        name: "菜脯煎蛋",
        price: 130,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0007_0007",
      },
      {
        name: "蝦仁煎蛋",
        price: 130,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0007_0008",
      },
      {
        name: "蔥花煎蛋",
        price: 130,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0007_0009",
      },
      {
        name: "番茄炒蛋",
        price: 130,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0007_0010",
      },
    ],
  },
  {
    address: "110台北市信義區忠孝東路四段553巷2弄9號",
    businessHour: ["11:00–20:00"],
    category: "eastern",
    phoneNumber: "+886227466212",
    title: "二代福林福州乾拌麵",
    photo: storeImg_8,
    id: "AAA0008",
    menu: [
      {
        name: "乾拌麵(小)",
        price: 40,
        class: "麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0001",
      },
      {
        name: "乾拌麵(大)",
        price: 55,
        class: "麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0002",
      },
      {
        name: "餛飩湯",
        price: 45,
        class: "湯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0003",
      },
      {
        name: "魚丸湯",
        price: 45,
        class: "湯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0004",
      },
      {
        name: "餛飩蛋包湯",
        price: 50,
        class: "湯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0005",
      },
      {
        name: "魚丸蛋包湯",
        price: 50,
        class: "湯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0006",
      },
      {
        name: "餛飩魚丸湯",
        price: 55,
        class: "湯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0007",
      },
      {
        name: "綜合湯",
        price: 60,
        class: "湯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0008",
      },
      {
        name: "蛋包湯",
        price: 25,
        class: "湯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0009",
      },
      {
        name: "紫菜湯",
        price: 30,
        class: "湯",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0010",
      },
      {
        name: "餛飩湯麵",
        price: 65,
        class: "湯麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0011",
      },
      {
        name: "魚丸湯麵",
        price: 65,
        class: "湯麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0012",
      },
      {
        name: "餛飩蛋包湯麵",
        price: 70,
        class: "湯麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0013",
      },
      {
        name: "魚丸蛋包湯麵",
        price: 70,
        class: "湯麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0014",
      },
      {
        name: "餛飩魚丸湯麵",
        price: 75,
        class: "湯麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0015",
      },
      {
        name: "綜合湯麵",
        price: 80,
        class: "湯麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0016",
      },
      {
        name: "蛋包湯麵",
        price: 50,
        class: "湯麵",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0017",
      },
      {
        name: "紅油抄手",
        price: 55,
        class: "抄手",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0018",
      },
      {
        name: "燙青菜-高麗菜",
        price: 40,
        class: "青菜",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0019",
      },
      {
        name: "燙青菜-大陸妹",
        price: 40,
        class: "青菜",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0020",
      },
      {
        name: "小菜",
        price: 35,
        class: "青菜",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0021",
      },
      {
        name: "紅油抄手麵",
        price: 75,
        class: "抄手",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0008_0022",
      },
    ],
  },
  {
    address: "110台北市信義區忠孝東路四段559巷16弄19號",
    businessHour: ["11:00–14:00", "16:30–19:00"],
    category: "eastern",
    phoneNumber: "+886227471433",
    title: "一記水餃牛肉麵店",
    photo: storeImg_9,
    id: "AAA0009",
    menu: [
      {
        name: "肉燥乾麵",
        price: 40,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0001",
      },
      {
        name: "肉燥湯麵",
        price: 40,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0002",
      },
      {
        name: "牛肉麵",
        price: 110,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0003",
      },
      {
        name: "牛肉湯麵",
        price: 65,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0004",
      },
      {
        name: "牛肉乾拌麵",
        price: 115,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0005",
      },
      {
        name: "榨菜肉絲麵",
        price: 60,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0006",
      },
      {
        name: "酸辣麵",
        price: 55,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0007",
      },
      {
        name: "酸辣湯餃(10粒)",
        price: 80,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0008",
      },
      {
        name: "牛肉湯餃(10粒)",
        price: 95,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0009",
      },
      {
        name: "高麗菜水餃",
        price: 55,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0010",
      },
      {
        name: "韭菜水餃",
        price: 55,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0011",
      },
      {
        name: "牛肉水餃",
        price: 75,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0012",
      },
      {
        name: "蝦仁水餃",
        price: 75,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0013",
      },
      {
        name: "酸辣湯",
        price: 30,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0014",
      },
      {
        name: "綜合丸子湯",
        price: 30,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0015",
      },
      {
        name: "蔬菜湯",
        price: 30,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0016",
      },
      {
        name: "牛肉湯(含菜)",
        price: 110,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0009_0017",
      },
    ],
  },
  {
    address: "110台北市信義區忠孝東路四段559巷16弄17號",
    businessHour: ["06:30–13:30"],
    category: "western",
    phoneNumber: "+886227666766",
    title: "真芳信義店",
    photo: storeImg_10,
    id: "AAA0010",
    menu: [
      {
        name: "真芳三明治",
        price: 90,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0010_0001",
      },
      {
        name: "豬肉蛋起司",
        price: 60,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0010_0002",
      },
      {
        name: "起司起司蛋",
        price: 50,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0010_0003",
      },
      {
        name: "真芳蛋餅",
        price: 30,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0010_0004",
      },
      {
        name: "辣肉蛋起司",
        price: 60,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0010_0005",
      },
      {
        name: "金瓜薯泥",
        price: 50,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0010_0006",
      },
      {
        name: "豬肉蛋",
        price: 50,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0010_0007",
      },
      {
        name: "花生花生",
        price: 40,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0010_0008",
      },
      {
        name: "煉乳起司",
        price: 40,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0010_0009",
      },
      {
        name: "榛果巧克力",
        price: 40,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0010_0010",
      },
      {
        name: "巧克力花生",
        price: 50,
        class: "單點",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0010_0011",
      },
      {
        name: "真芳紅茶",
        price: 30,
        class: "飲料",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0010_0012",
      },
      {
        name: "紅茶牛奶",
        price: 45,
        class: "飲料",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0010_0013",
      },
      {
        name: "美式咖啡",
        price: 40,
        class: "飲料",
        sizeOption: false,
        sizeAndPrice: null,
        id: "AAA0010_0014",
      },
    ],
  },
  {
    address: "10658台北市大安區信義路三段190號1樓",
    businessHour: ["10:00–22:00"],
    category: "beverage",
    phoneNumber: "+886227557655",
    title: "麻古茶坊",
    photo: storeImg_11,
    id: "AAA0011",
    menu: [
      {
        name: "百香雙Q果",
        price: null,
        class: "鮮果茶飲",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 60, canChooseIce: true },
          { size: "Bottle", price: 90, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0001",
      },
      {
        name: "百香綠茶",
        price: null,
        class: "鮮果茶飲",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 60, canChooseIce: true },
          { size: "Bottle", price: 90, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0002",
      },
      {
        name: "百香多多",
        price: null,
        class: "鮮果茶飲",
        sizeOption: true,
        sizeAndPrice: [{ size: "L", price: 65, canChooseIce: true }],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0003",
      },
      {
        name: "翡翠香橙",
        price: null,
        class: "鮮果茶飲",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 65, canChooseIce: true },
          { size: "Bottle", price: 95, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0004",
      },
      {
        name: "翡翠柳橙",
        price: null,
        class: "鮮果茶飲",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 65, canChooseIce: true },
          { size: "Bottle", price: 95, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0005",
      },
      {
        name: "冰萃檸檬",
        price: null,
        class: "鮮果茶飲",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 50, canChooseIce: true },
          { size: "L(熱)", price: 50, canChooseIce: false },
        ],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0006",
      },
      {
        name: "檸檬綠茶/紅茶",
        price: null,
        class: "鮮果茶飲",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 45, canChooseIce: true },
          { size: "L(熱)", price: 45, canChooseIce: false },
        ],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0007",
      },
      {
        name: "蜂蜜檸檬",
        price: null,
        class: "鮮果茶飲",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 60, canChooseIce: true },
          { size: "L(熱)", price: 60, canChooseIce: false },
        ],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0008",
      },
      {
        name: "檸檬多多",
        price: null,
        class: "鮮果茶飲",
        sizeOption: true,
        sizeAndPrice: [{ size: "L", price: 60, canChooseIce: true }],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0009",
      },
      {
        name: "檸檬梅子",
        price: null,
        class: "鮮果茶飲",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 55, canChooseIce: true },
          { size: "L(熱)", price: 55, canChooseIce: false },
        ],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0010",
      },
      {
        name: "楊枝甘露2.0",
        price: null,
        class: "季節限定",
        sizeOption: true,
        sizeAndPrice: [{ size: "L(碎冰沙)", price: 75, canChooseIce: false }],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0011",
      },
      {
        name: "芝芝芒果果粒",
        price: null,
        class: "季節限定",
        sizeOption: true,
        sizeAndPrice: [{ size: "L(碎冰沙)", price: 90, canChooseIce: false }],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0012",
      },
      {
        name: "芝芝草莓果粒",
        price: null,
        class: "季節限定",
        sizeOption: true,
        sizeAndPrice: [{ size: "L(冰沙)", price: 90, canChooseIce: false }],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0013",
      },
      {
        name: "芝芝葡萄果粒",
        price: null,
        class: "季節限定",
        sizeOption: true,
        sizeAndPrice: [{ size: "L(冰沙)", price: 85, canChooseIce: false }],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0014",
      },
      {
        name: "香橙果粒茶",
        price: null,
        class: "果粒茶系列",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 60, canChooseIce: true },
          { size: "Bottle", price: 90, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0015",
      },
      {
        name: "柳橙果粒茶",
        price: null,
        class: "果粒茶系列",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 60, canChooseIce: true },
          { size: "Bottle", price: 90, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0016",
      },
      {
        name: "葡萄柚果粒茶",
        price: null,
        class: "果粒茶系列",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 55, canChooseIce: true },
          { size: "Bottle", price: 85, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0017",
      },
      {
        name: "葡萄柚果粒蜜茶",
        price: null,
        class: "果粒茶系列",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 55, canChooseIce: true },
          { size: "Bottle", price: 85, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0018",
      },
      {
        name: "葡萄柚果粒多多",
        price: null,
        class: "果粒茶系列",
        sizeOption: true,
        sizeAndPrice: [{ size: "L", price: 65, canChooseIce: true }],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0019",
      },
      {
        name: "奇異果果粒茶",
        price: null,
        class: "果粒茶系列",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 65, canChooseIce: true },
          { size: "Bottle", price: 100, canChooseIce: true },
        ],
        sugar: ["無糖", "一分糖", "三分糖", "半糖", "八分糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0011_0020",
      },
    ],
  },
  {
    address: "110台北市信義區永吉路30巷123號",
    businessHour: ["10:00–22:00"],
    category: "beverage",
    phoneNumber: "+886227668608",
    title: "約翰紅茶",
    photo: storeImg_12,
    id: "AAA0012",
    menu: [
      {
        name: "康提紅茶",
        price: null,
        class: "紅茶經典",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 25, canChooseIce: true },
          { size: "L", price: 30, canChooseIce: true },
        ],
        sugar: ["無糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0012_0001",
      },
      {
        name: "雨果紅茶",
        price: null,
        class: "紅茶經典",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 30, canChooseIce: true },
          { size: "L", price: 35, canChooseIce: true },
          { size: "M（熱）", price: 35, canChooseIce: false },
        ],
        sugar: ["無糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0012_0002",
      },
      {
        name: "曼非紅茶",
        price: null,
        class: "紅茶經典",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 30, canChooseIce: true },
          { size: "L", price: 35, canChooseIce: true },
          { size: "M（熱）", price: 35, canChooseIce: false },
        ],
        sugar: ["無糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0012_0003",
      },
      {
        name: "茶中香檳",
        price: null,
        class: "紅茶經典",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 35, canChooseIce: true },
          { size: "L", price: 40, canChooseIce: true },
          { size: "M（熱）", price: 40, canChooseIce: false },
        ],
        sugar: ["無糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0012_0004",
      },
      {
        name: "錫金紅茶",
        price: null,
        class: "紅茶經典",
        sizeOption: true,
        sizeAndPrice: [{ size: "M", price: 45, canChooseIce: true }],
        sugar: ["無糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0012_0005",
      },
      {
        name: "夢幻紅茶",
        price: null,
        class: "紅茶經典",
        sizeOption: true,
        sizeAndPrice: [{ size: "M", price: 50, canChooseIce: true }],
        sugar: ["無糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0012_0006",
      },
      {
        name: "珍珠那提",
        price: null,
        class: "紅茶那提",
        sizeOption: true,
        sizeAndPrice: [
          { size: "L", price: 60, canChooseIce: true },
          { size: "M（熱）", price: 60, canChooseIce: false },
        ],
        sugar: ["無糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0012_0007",
      },
      {
        name: "雨果那提",
        price: null,
        class: "紅茶那提",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 50, canChooseIce: true },
          { size: "L", price: 55, canChooseIce: true },
          { size: "M（熱）", price: 55, canChooseIce: false },
        ],
        sugar: ["無糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0012_0008",
      },
      {
        name: "曼非那提",
        price: null,
        class: "紅茶那提",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 50, canChooseIce: true },
          { size: "L", price: 55, canChooseIce: true },
          { size: "M（熱）", price: 55, canChooseIce: false },
        ],
        sugar: ["無糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0012_0009",
      },
      {
        name: "烏瓦那提",
        price: null,
        class: "紅茶那提",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 55, canChooseIce: true },
          { size: "L", price: 60, canChooseIce: true },
          { size: "M（熱）", price: 60, canChooseIce: false },
        ],
        sugar: ["無糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0012_0010",
      },
      {
        name: "抹茶那提",
        price: null,
        class: "紅茶那提",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 60, canChooseIce: true },
          { size: "M（熱）", price: 60, canChooseIce: false },
        ],
        sugar: ["無糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0012_0011",
      },
      {
        name: "煮濃那提",
        price: null,
        class: "紅茶那提",
        sizeOption: true,
        sizeAndPrice: [{ size: "M", price: 60, canChooseIce: true }],
        sugar: ["無糖", "微糖", "半糖", "少糖", "正常糖"],
        ice: ["去冰", "微冰", "少冰", "正常冰"],
        id: "AAA0012_0012",
      },
    ],
  },

  //  {
  //     address: "110台北市信義區忠孝東路四段559巷16弄2-1號",
  //     businessHour: ["07:00–17:00"],
  //     category: "eastern",
  //     phoneNumber: "+886227535278",
  //     title: "凱琳手作蛋餅和羋亞瓦特",
  //     menu: []
  //  },
  //  {
  //     address: "11072台北市信義區忠孝東路四段559巷12號",
  //     businessHour: ["11:00–19:00"],
  //     category: "beverage",
  //     phoneNumber: "+886227650696",
  //     title: "瓷禧茶坊",
  //     menu: []
  //  },
  //  {
  //     address: "110台北市信義區忠孝東路四段559巷16弄11號",
  //     businessHour: ["unknow"],
  //     category: "eastern",
  //     phoneNumber: "+886227661938",
  //     title: "廣東燒臘燴飯快餐",
  //     menu: []
  //  },
  //  {
  //     address: "110台北市信義區忠孝東路四段553巷52弄5號1樓",
  //     businessHour: ["11:30–15:30", "17:30-21:00"],
  //     category: "cantonese",
  //     phoneNumber: "+886237621195",
  //     title: "龍星冰室",
  //     menu: []
  //  },
  //  {
  //     address: "110台北市信義區忠孝東路五段17-1號",
  //     businessHour: ["10:00–22:00"],
  //     category: "beverage",
  //     phoneNumber: "+886227423896",
  //     title: "珍煮丹",
  //     menu: []
  //  },
  //  {
  //     address: "11064台北市信義區基隆路一段147巷5弄13號",
  //     businessHour: ["11:30–15:00", "17:30–22:00"],
  //     category: "western",
  //     phoneNumber: "+886227661891",
  //     title: "新義法料理",
  //     menu: []
  //  },
  //  {
  //     address: "110台北市信義區忠孝東路四段559巷16弄15號",
  //     businessHour: ["09:00–14:00"],
  //     category: "eastern",
  //     phoneNumber: "+886227651127",
  //     title: "杜佬大手作弁當",
  //     menu: []
  //  },
];
export default data;

// {name: "",price: null,class: "",sizeOption: true,sizeAndPrice: [{ size: "L", price:  },{ size: "Bottle", price:  }],sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"]},
// {name: "",price: 65,class: "",sizeOption: false,sizeAndPrice: null,sugar: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"]},
