const data = [
  {
    address: "110台北市信義區松仁路253巷1弄2號",
    businessHour: ["10:30–20:00"],
    category: "healthy",
    phoneNumber: "+886227207471",
    title: "橄欖油健康餐盒",
    photo: "id",
    menu: [
      { name: "舒肥墨西哥烤", price: 180, class: "經典舒肥系列" },
      { name: "法式舒肥櫻桃鴨胸", price: 230, class: "經典舒肥系列" },
      { name: "舒肥雞肉輕食餐", price: 150, class: "經典舒肥系列" },
      { name: "舒肥牛小排輕食餐", price: 260, class: "經典舒肥系列" },
      { name: "舒肥鮭魚菲力輕食餐", price: 260, class: "經典舒肥系列" },
      { name: "紅酒燉牛肋條", price: 190, class: "燉肉餐盒" },
      { name: "獵人燉雞腿", price: 150, class: "燉肉餐盒" },
      { name: "DELI法式櫻桃鴨沙拉", price: 230, class: "沙拉" },
      { name: "DELI墨西哥烤豬沙拉", price: 180, class: "沙拉" },
      { name: "DELI 水果生菜沙拉", price: 150, class: "沙拉" },
      { name: "DELI 雞胸肉沙拉", price: 150, class: "沙拉" },
      { name: "DELI 牛小排沙拉", price: 260, class: "沙拉" },
      { name: "DELI 鮭魚沙拉", price: 260, class: "沙拉" },
      { name: "地中海風味當季時蔬", price: 180, class: "素食餐盒" },
      { name: "南瓜濃湯", price: 80, class: "湯品" },
      { name: "義式蔬菜湯（素）", price: 60, class: "湯品" },
      { name: "法式洋蔥湯", price: 60, class: "湯品" },
      { name: "美式咖啡", price: 50, class: "飲料" },
      { name: "甜菊紅茶", price: 35, class: "飲料" },
      { name: "蜂蜜檸檬汁（冰）", price: 65, class: "飲料" },
      { name: "水煮蛋", price: 20, class: "單點" },
      { name: "低溫雞胸肉", price: 60, class: "單點" },
      { name: "低溫牛小排", price: 190, class: "單點" },
      { name: "低溫鮭魚菲力", price: 190, class: "單點" },
    ],
  },
  {
    address: "110台北市信義區忠孝東路四段553巷2弄5號",
    businessHour: [" 11:30–21:00"],
    category: "western",
    phoneNumber: "+886227531881",
    title: "一直是晴天",
    menu: [
      { name: "卡哩卡哩雞腿沙拉", price: 200, class: "早午餐、沙拉餐" },
      { name: "碳烤牛肉沙拉", price: 200, class: "早午餐、沙拉餐" },
      { name: "手工蔥餅佐醬燒牛肉", price: 220, class: "早午餐、沙拉餐" },
      { name: "香煎松阪豬沙拉", price: 220, class: "早午餐、沙拉餐" },
      { name: "煎烤牛小排沙拉", price: 320, class: "早午餐、沙拉餐" },
      { name: "義式炒海鮮沙拉", price: 320, class: "早午餐、沙拉餐" },
      { name: "檸香雞腿飯", price: 200, class: "吃飯飯" },
      { name: "碳烤牛肉飯", price: 200, class: "吃飯飯" },
      { name: "塔香咕咕雞", price: 200, class: "吃飯飯" },
      { name: "煎烤牛小排飯", price: 300, class: "吃飯飯" },
      { name: "鮮蔬什錦丼飯", price: 200, class: "吃飯飯" },
      { name: "時蔬衝爆牛肉飯", price: 220, class: "吃飯飯" },
      { name: "香煎松阪豬佐時蔬", price: 220, class: "吃飯飯" },
      { name: "招牌蕃茄肉醬義大利麵", price: 180, class: "吃麵麵" },
      { name: "和風柚香鮮蔬義大利麵", price: 180, class: "吃麵麵" },
      { name: "辣味轟炸雞義大利麵", price: 200, class: "吃麵麵" },
      { name: "蒜香煎烤雞肉義大利麵", price: 200, class: "吃麵麵" },
      { name: "義式雪花牛肉義大利麵", price: 200, class: "吃麵麵" },
      { name: "酥炸花枝蒜辣義大利麵", price: 200, class: "吃麵麵" },
      { name: "蒜香煎烤牛小排義大利麵", price: 300, class: "吃麵麵" },
      { name: "爆蒜辣炒海鮮義大利麵", price: 300, class: "吃麵麵" },
    ],
  },
  {
    address: "台北市信義區基隆路二段10號",
    businessHour: ["17:00-03:00"],
    category: "western",
    phoneNumber: "8786-8858",
    title: "角窩美式餐酒館",
    menu: [
      { name: "凱薩沙拉", price: 180, class: "沙拉" },
      { name: "雞肉沙拉", price: 200, class: "沙拉" },
      { name: "⽜肉沙拉", price: 220, class: "沙拉" },
      { name: "醬烤雞胸古巴三明治", price: 300, class: "古巴三明治" },
      { name: "黑咖⼿撕豬古巴三明治", price: 320, class: "古巴三明治" },
      { name: "悶烤⽜胸古巴三明治", price: 380, class: "古巴三明治" },
      { name: "工人放飯", price: 200, class: "角窩鍋飯" },
      { name: "工頭開飯", price: 220, class: "角窩鍋飯" },
      { name: "加州海鮮比薩", price: 280, class: "8寸比薩" },
      { name: "夏威夷比薩", price: 250, class: "8寸比薩" },
      { name: "墨西哥臘腸比", price: 280, class: "8寸比薩" },
      { name: "燻烤豬肋排", price: 450, class: "排餐" },
      { name: "加州風味雞腿排", price: 390, class: "排餐" },
    ],
  },
  {
    address: "110台北市信義區忠孝東路四段553巷2弄11號",
    businessHour: ["10:30–14:00", "15:00–19:00"],
    category: "healthy",
    phoneNumber: "+886227669669",
    title: "給力盒子",
    menu: [
      { name: "墨西哥火烤雞胸", price: 158, class: "人氣精選" },
      { name: "蒜泥低脂豬肉片", price: 148, class: "人氣精選" },
      { name: "香蒜水煮雞胸", price: 158, class: "人氣精選" },
      { name: "義式香草烤雞腿排", price: 168, class: "人氣精選" },
      { name: "肉多多特餐", price: 178, class: "人氣精選" },
    ],
  },
  {
    address: "110台北市信義區忠孝東路五段17之2號",
    businessHour: ["10:00–22:00"],
    category: "beverage",
    phoneNumber: "+886227680808",
    title: "可不可",
    menu: [
      {
        name: "熟成紅茶",
        price: null,
        class: "紅茶",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 25 },
          { size: "L", price: 30 },
        ],
        suger: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        size: ["M", "L"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
      },
      {
        name: "麗春紅茶",
        price: null,
        class: "紅茶",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 25 },
          { size: "L", price: 30 },
        ],
        suger: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        size: ["M", "L"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
      },
      {
        name: "太妃紅茶",
        price: null,
        class: "紅茶",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 30 },
          { size: "L", price: 35 },
        ],
        suger: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        size: ["M", "L"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
      },
      {
        name: "胭脂紅茶",
        price: null,
        class: "紅茶",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 35 },
          { size: "L", price: 40 },
        ],
        suger: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        size: ["M", "L"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
      },
      {
        name: "雪藏紅茶",
        price: null,
        class: "紅茶",
        sizeOption: true,
        sizeAndPrice: [
          { size: "M", price: 45 },
          { size: "L", price: 55 },
        ],
        suger: ["無糖", "一分糖", "二分糖", "微糖", "半糖", "少糖", "正常糖"],
        size: ["M", "L"],
        ice: ["去冰", "微冰", "少冰", "正常冰", "常溫", "溫", "熱"],
      },
    ],
  },
  {
    address: "110台北市信義區忠孝東路四段559巷18之1號",
    businessHour: ["11:00–20:30"],
    category: "eastern",
    phoneNumber: "+886227493472",
    title: "味家魯肉飯",
    menu: [
      { name: "舌頭肉", price: 50, class: "單點" },
      { name: "豬舌頭", price: 50, class: "單點" },
      { name: "豬肝𦟪", price: 50, class: "單點" },
      { name: "滷蛋", price: 10, class: "單點" },
      { name: "油豆腐", price: 10, class: "單點" },
      { name: "白菜滷", price: 30, class: "單點" },
      { name: "筍絲", price: 30, class: "單點" },
      { name: "燙青菜", price: 30, class: "單點" },
      { name: "肉燥乾油麵", price: 45, class: "單點" },
      { name: "肉燥乾米粉", price: 45, class: "單點" },
      { name: "肉羹麵", price: 50, class: "單點" },
      { name: "肉羹米粉", price: 50, class: "單點" },
      { name: "肉羹冬粉", price: 50, class: "單點" },
      { name: "肉羹", price: 40, class: "單點" },
      { name: "排骨酥湯麵", price: 55, class: "單點" },
      { name: "排骨酥湯米粉", price: 55, class: "單點" },
      { name: "排骨酥湯冬粉", price: 55, class: "單點" },
      { name: "鳳梨苦瓜雞湯", price: 50, class: "單點" },
      { name: "蛤仔雞湯", price: 50, class: "單點" },
      { name: "排骨酥湯", price: 45, class: "單點" },
      { name: "筒仔米糕", price: 30, class: "單點" },
      { name: "控肉飯", price: 80, class: "單點" },
      { name: "魯肉飯便當", price: 75, class: "單點" },
      { name: "魯肉飯（大）", price: 40, class: "單點" },
      { name: "魯肉飯（小）", price: 25, class: "單點" },
    ],
  },
  {
    address: "110台北市信義區忠孝東路四段559巷16弄7號",
    businessHour: ["unknow"],
    category: "eastern",
    phoneNumber: "+886227458198",
    title: "台灣阿誠現炒菜",
    menu: [
      { name: "牛肉蛋炒飯", price: 90, class: "單點" },
      { name: "蝦仁肉絲蛋炒飯", price: 90, class: "單點" },
      { name: "海鮮什錦炒麵", price: 90, class: "單點" },
      { name: "牛肉炒麵", price: 90, class: "單點" },
      { name: "肉絲炒麵", price: 90, class: "單點" },
      { name: "招牌煎蛋", price: 130, class: "單點" },
      { name: "菜脯煎蛋", price: 130, class: "單點" },
      { name: "蝦仁煎蛋", price: 130, class: "單點" },
      { name: "蔥花煎蛋", price: 130, class: "單點" },
      { name: "番茄炒蛋", price: 130, class: "單點" },
    ],
  },
  {
    address: "110台北市信義區忠孝東路四段553巷2弄9號",
    businessHour: ["11:00–20:00"],
    category: "eastern",
    phoneNumber: "+886227466212",
    title: "二代福林福州乾拌麵",
    menu: [
      { name: "乾拌麵(小)", price: 40, class: "單點" },
      { name: "乾拌麵(大)", price: 55, class: "單點" },
    ],
  },
  {
    address: "110台北市信義區忠孝東路四段559巷16弄19號",
    businessHour: ["11:00–14:00", "16:30–19:00"],
    category: "eastern",
    phoneNumber: "+886227471433",
    title: "一記水餃牛肉麵店",
  },
  {
    address: "110台北市信義區忠孝東路四段559巷16弄17號",
    businessHour: ["06:30–13:30"],
    category: "western",
    phoneNumber: "+886227666766",
    title: "真芳信義店",
  },
  {
    address: "10658台北市大安區信義路三段190號1樓",
    businessHour: ["10:00–22:00"],
    category: "beverage",
    phoneNumber: "+886227557655",
    title: "麻古茶坊",
  },
  {
    address: "110台北市信義區忠孝東路四段559巷14號",
    businessHour: ["06:00–13:00"],
    category: "eastern",
    phoneNumber: "+886287877108",
    title: "米奇早餐店",
  },
  {
    address: "110台北市信義區忠孝東路四段559巷16弄6號",
    businessHour: ["11:30–20:30"],
    category: "western",
    phoneNumber: "+886227613600",
    title: "比利時咖啡",
  },
  {
    address: "110台北市信義區永吉路30巷123號",
    businessHour: ["10:00–22:00"],
    category: "beverage",
    phoneNumber: "+886227668608",
    title: "約翰紅茶",
  },
  {
    address: "110台北市信義區忠孝東路四段559巷16弄2-1號",
    businessHour: ["07:00–17:00"],
    category: "eastern",
    phoneNumber: "+886227535278",
    title: "凱琳手作蛋餅和羋亞瓦特",
  },
  {
    address: "11072台北市信義區忠孝東路四段559巷12號",
    businessHour: ["11:00–19:00"],
    category: "beverage",
    phoneNumber: "+886227650696",
    title: "瓷禧茶坊",
  },
  {
    address: "110台北市信義區忠孝東路四段559巷16弄11號",
    businessHour: ["unknow"],
    category: "eastern",
    phoneNumber: "+886227661938",
    title: "廣東燒臘燴飯快餐",
  },
  {
    address: "110台北市信義區忠孝東路四段553巷52弄5號1樓",
    businessHour: ["11:30–15:30", "17:30-21:00"],
    category: "cantonese",
    phoneNumber: "+886237621195",
    title: "龍星冰室",
  },
  {
    address: "110台北市信義區忠孝東路五段17-1號",
    businessHour: ["10:00–22:00"],
    category: "beverage",
    phoneNumber: "+886227423896",
    title: "珍煮丹",
  },
  {
    address: "11064台北市信義區基隆路一段147巷5弄13號",
    businessHour: ["11:30–15:00", "17:30–22:00"],
    category: "western",
    phoneNumber: "+886227661891",
    title: "新義法料理",
  },
  {
    address: "110台北市信義區忠孝東路四段559巷16弄15號",
    businessHour: ["09:00–14:00"],
    category: "eastern",
    phoneNumber: "+886227651127",
    title: "杜佬大手作弁當",
  },
  {
    address: "110台北市信義區忠孝東路四段553巷2弄11號",
    businessHour: ["10:30–14:00", "15:00–19:00"],
    category: "healthy",
    phoneNumber: "+886227669669",
    title: "給力盒子",
  },
];
export default data;
